### ISSUE TITLE
请问下jetpack 5.0的正确升级方式以及该refactor脚本的使用方法

### ISSUE THREAD

**Issue by LJM2018** [zbwu/athena_l4t_sdk#1]
A姐你好，我最近在看你这个refactor的repo，但是在升级过程遇到了些问题想请教下，我的狗刷了最新的10094固件后，尝试根据[海总的方法](https://github.com/MiRoboticsLab/cyberdog_ros2/discussions/110)把jetpack 从默认的32.5升级到34.1(对应jetpack 5.0)，apt upgrade 跳出来近3个G的update，但是升级过后，再去sudo apt install nvidia-jetpack怎么都安装不了，显示以下error
![image](https://user-images.githubusercontent.com/35580709/177008373-a5c64bcf-de03-4dfe-8c45-3395634e891a.png)
我仔细看了上面几个提到的pkg，apt show显示版本都对，但就是unmet dependencies，不知道是不是因为我升级跨度太大了导致，想问下你当时怎么升级的，可以update到你的readme吗

第二个是关于你的refactor项目的，我看了下感觉你的这个脚本是在host端直接线刷铁蛋用的？可以简单讲下怎么使用吗，感谢！

**Comment by zbwu** [comment]
在Cyberdog上直接用apt升级到JP5是不可行的，因为小米官方没有提供JP5对应的Linux kernel。为了避免出现不可预测的情况，估计小米也lock了apt包，导致升级依赖不完整从而避免升级失败（根据上面的log纯推测）。

我重构的版本目前只能用usb更新，这是几个原因导致的，首先是目前JP5的Preview版本只能用usb更新（因为底层变动较大，具体参考官方文档），其次是这个重构版本主要针对开发者没有太多考虑产品化的细节， 等等

准备好系统环境（参考官方文档）和网络环境，按顺序执行Readme最下面的几个脚本就能编译和生成镜像。

**Comment by LJM2018** [comment]
![image](https://user-images.githubusercontent.com/35580709/180657361-379955fa-ec87-4545-a7de-bf1891415dd9.png)

![image](https://user-images.githubusercontent.com/35580709/180657401-61a5e214-b160-434a-8bae-878880995b22.png)

谢谢A姐提示，我尝试用SDK manager去下载image并把repo里你修改的脚本放进同个文件夹，第一步build samplefs 成功了，但是build_athena_kernel。sh就直接报了找不到文件，我觉得应该是我miss了什么重要步骤lol，可以提示下我哪个环节漏了吗，第一次flash jetson，看官方的文档也是寥寥几步就说完了感觉有点lost，多谢！
